import './globals.css';
import { Quattrocento, Lato } from 'next/font/google';
// import { Inter } from 'next/font/google';

const quattrocento = Quattrocento({
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-quattrocento',
});

const lato = Lato({
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lato',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <body className={quattrocento.className}>{children}</body> */}
      <body className={`${quattrocento.variable} ${lato.variable}`}>
        {children}
      </body>
    </html>
  );
}
